### ISSUE TITLE
How to use UCMCTracker on custom video.

### ISSUE THREAD

**Issue by shreejalt** [corfyi/UCMCTrack#16]
Hi, 
I wanted your help in running the tracker on the custom video. I will use the frame of that video to calibrate using your tool. Can you please guide me on running your tracker on any video?

**Comment by corfyi** [comment]
Thank you for reaching out and expressing interest in using our tracker with your custom video. Here's a step-by-step guide to help you get started:

1. **Camera Parameter Estimation**: First, you'll need to estimate the camera parameters from a frame extracted from your video. You can do this by running the script with the command:
   
   ```
   python util/estimate_cam_para.py --img your_video_frame.jpg --cam_para your_cam_para.txt
   ```

   This will use a frame (`your_video_frame.jpg`) extracted from your video to estimate the camera parameters, which will be saved in `your_cam_para.txt`. For detailed instructions on how to perform this step, please refer to the 'Camera Parameter Estimation Tool' section in our README.

2. **Running the Tracker**: Once you have the camera parameters estimated, you can run the tracker on your video by executing the following script:

   ```
   python demo.py --cam_para your_cam_para.txt --video your_video.mp4
   ```

   This command will start the tracker using the camera parameters you've estimated (`your_cam_para.txt`) and apply it to your video (`your_video.mp4`).

Please ensure that you have followed all the setup instructions mentioned in our README to avoid any potential issues. If you encounter any problems or have further questions, don't hesitate to ask.

**Comment by shreejalt** [comment]
@corfyi 
Thanks a lot for your response. I had some questions regarding the camera parameter estimation tool.
When I run the command:
`python util/estimate_cam_para.py --img your_video_frame.jpg --cam_para your_cam_para.txt
`

Does it give the camera parameters directly, or do I need to align the `fx`, `fy`, and `fz`, and focal length parameters?
If yes then for me it is not clear that what alignment looks right when I use the tool. For eg, how should a right focal length look like, can you give me an example?

**Comment by corfyi** [comment]
I recommend referring to the discussion in issue #6. There, we have addressed similar concerns and provided comprehensive instructions that should be helpful in your case.

**Comment by shreejalt** [comment]
Hi @corfyi 
I think it is not mentioned in #6. What I am asking that after I get the initial parameters, how can we judge or change the parameters using GUI such as focal length becuase when I increase the focal length the dots on the image go far away which assumes that we are zooming in.

So I am asking that after I run your code on my custom image, I get some parameters, but I have to further tune to get the exact params for fx, fy, fz and focal length. Can you please give me some idea that how to judgethat the tuned parameters are correct?

**Comment by corfyi** [comment]
Our tool allows for the modification of camera extrinsic parameters, specifically the rotation angles, but does not account for translation. It provides a rough estimate of camera parameters, which, while not precise, has been shown to achieve good tracking results with UCMCTrack even with this level of approximation. It's important to note that achieving an exact estimation of camera parameters based on a single image is challenging. This is because a single image offers limited information, making it difficult to accurately assess the precision of the estimations.

Our approach primarily offers a way to get a rough starting point for these parameters. The visual feedback you mentioned, such as the effect of zooming when adjusting the focal length, can serve as a qualitative guide. However, due to the inherent limitations of estimating camera parameters from a single image, exact accuracy and evaluation of these parameters can be complex.
