### ISSUE TITLE
關於FPS比較

### ISSUE THREAD

**Issue by geoxpert0001** [corfyi/UCMCTrack#18]
謝謝作者開源
雖然準確是最大的評估標準 但整體運行速度也要考量
在論文裡面 似乎沒有看到FPS數據
不曉得UCMC 速度跟botsort vs bytetrack 哪個快

botsort < bytetrack (速度)

**Comment by corfyi** [comment]
Our method may be slightly slower than ByteTrack without ReID due to the higher computational complexity of the Mahalanobis distance compared to the IoU distance. Our method is faster than BoTSORT because we do not use any appearance information.

Using the pre-existing detection results (excluding the inference time of yolox), the C++ version of our algorithm achieves over 1000 FPS on the MOT17 dataset and between 300-1000 FPS on the MOT20 dataset (depending on the number of detections). The Python version, which has not been optimized for speed, runs approximately ten times slower than the C++ version.

We appreciate your interest in our work and encourage you to star our repository if you find it useful. Thank you for your support!
