### ISSUE TITLE
About Camera Parameters

### ISSUE THREAD

**Issue by DKYxdd** [corfyi/UCMCTrack#5]
Thanks for your great work!  
"For MOT17, MOT20, and DanceTrack datasets, we manually estimated the camera parameters since they are not publicly accessible" refered to your paper.  So I want to know these IntrinsicMatrix and ExtrinsicMatrix in ./cam_para all like the hyperparameters that are manually estimated ？ It sounds like a huge task.
Hope for your reply, Thank u!

**Comment by corfyi** [comment]
To address your question, yes, the IntrinsicMatrix and ExtrinsicMatrix provided in the ./cam_para directory were manually estimated by us for the MOT17, MOT20, and DanceTrack datasets, as the original camera parameters were not publicly available. 

We understand that estimating camera parameters can be a complex task, which is why we have developed a tool that can automatically estimate both the intrinsic and extrinsic parameters from a single image. This tool has been designed to be user-friendly and efficient, allowing for quick and accurate estimation of these parameters for various datasets.

The estimated camera parameters, although not exact, have proven to be effective for our UCMCTrack method, as they provide a good approximation of the actual camera settings. We believe that this approximation is sufficient for our purposes, as it allows us to achieve robust tracking results even with imperfect camera parameters.

We are pleased to inform you that we plan to open-source this camera parameter estimation tool in the near future. This will give you the opportunity to try it out and see how it works for yourself. We hope that this tool will be useful not only for our research but also for the wider computer vision community.

Thank you again for your interest in our work. We look forward to sharing more details about the tool and its performance in the coming weeks. If you have any further questions or comments, please feel free to reach out to us.

**Comment by DKYxdd** [comment]
Thank u for your reply！ @corfyi
